"""empty message

Revision ID: 6e1db5433cbb
Revises: 6fc7fc4ca974
Create Date: 2017-05-22 14:26:59.419627

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6e1db5433cbb'
down_revision = '6fc7fc4ca974'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('bio', sa.Text(), nullable=True))
    op.add_column('users', sa.Column('header_image_url', sa.Text(), nullable=True))
    op.add_column('users', sa.Column('location', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'location')
    op.drop_column('users', 'header_image_url')
    op.drop_column('users', 'bio')
    # ### end Alembic commands ###
